### ISSUE TITLE
Update all labels for Predictive Repo

### ISSUE THREAD

**Issue by pringlized** [machinelearningsanfrancisco/San-Francisco-Traffic-Predictive-Model#3]
[Template ](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63)to start from.

**Comment by pringlized** [comment]
Eventually, we will have new projects/repos that won't have the labels.  Using ZenHub can take care of that problem by bundling all future repos into a Workspace.

**Comment by pringlized** [comment]
Done but the colors could use some tweaking.

**Comment by VictorGFranco** [comment]
Good job on the colors.

**Comment by VictorGFranco** [comment]
Just changed the in progress label to hot pink. everything else is fine
